name: Print Hello World

on:
  push:
    branches: [ '*' ]  # Trigger on push to any branch

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello World
      run: echo "Hello World"
